config/routes.rb
Eyeloupe::Engine.routes.draw do

  root to: "application#root"

  resources :in_requests, only: [:index, :show]
  resources :out_requests, only: [:index, :show]
  resources :exceptions, only: [:index, :show]
  resources :jobs, only: [:index, :show]
  resources :ai_assistant_responses, only: [:show]

  resource :data, only: [:destroy]

  resource :configs, only: [:update]

end

app/models/eyeloupe/application_record.rb
module Eyeloupe
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    if Eyeloupe.configuration.database
      connects_to database: { writing: Eyeloupe.configuration.database.to_sym, reading: Eyeloupe.configuration.database.to_sym }
    end
  end
end

app/models/eyeloupe/exception.rb
module Eyeloupe
  class Exception < ApplicationRecord
    has_one :in_request, class_name: "Eyeloupe::InRequest"
    has_one :out_request, class_name: "Eyeloupe::OutRequest"
  end
end

app/models/eyeloupe/in_request.rb
module Eyeloupe
  class InRequest < ApplicationRecord
    has_one :exception, class_name: "Eyeloupe::Exception"
  end
end

app/models/eyeloupe/job.rb
module Eyeloupe
  class Job < ApplicationRecord
    validates :job_id, uniqueness: true

    enum status: [:enqueued, :running, :completed, :failed, :discarded]
  end
end

app/models/eyeloupe/out_request.rb
module Eyeloupe
  class OutRequest < ApplicationRecord
    has_one :exception, class_name: "Eyeloupe::Exception"
  end
end

app/controllers/concerns/eyeloupe/searchable.rb
# frozen_string_literal: true

module Eyeloupe
  module Searchable
    extend ActiveSupport::Concern

    path_models = %w[InRequest OutRequest]
    name_models = %w[Job]

    included do
      before_action :set_query, only: [:index]
    end

    protected

    def set_query
      model = ("Eyeloupe::" + controller_name.classify).constantize
      where = model.attribute_names.include?("path") ? 'path' : 'classname'
      @query = params[:q].present? ? model.where("#{where} LIKE ?", "%#{params[:q].strip}%").order(created_at: :desc)
                 : model.all.order(created_at: :desc)
    end
  end

end

app/controllers/eyeloupe/ai_assistant_responses_controller.rb
# frozen_string_literal: true

module Eyeloupe
  class AiAssistantResponsesController < ApplicationController

    before_action :set_exception, only: %i[ show ]

    def show
      client = OpenAI::Client.new

      code = File.read(@exception.file)

      @response = client.chat(
        parameters: {
          model: Eyeloupe::configuration.openai_model,
          messages: [{"role": "system", "content": "You are a Ruby on Rails software developer, you develop software programs and applications using programming languages like Ruby and Ruby on Rails and development tools."},
                     {"role": "user", "content": "I have a problem with my Ruby on Rails application. I am getting an error message that says:  #{@exception.kind} #{@exception.message}. Here is my code, the error is in line #{@exception.line}: #{code}. Answer as concise as possible. Show me resulting code. The response should in Markdown format."}],
          temperature: 0.7
        })

      render json: @response
    end

    private

    def set_exception
      @exception = Exception.find(params[:id])
    end
  end
end

app/controllers/eyeloupe/application_controller.rb
module Eyeloupe
  class ApplicationController < ActionController::Base
    include Pagy::Backend

    before_action :set_config

    def root
      redirect_to in_requests_path
    end

    protected

    def set_config
      @eyeloupe_capture = cookies[:eyeloupe_capture].present? ? cookies[:eyeloupe_capture] == "true" : Eyeloupe.configuration.capture
    end
  end
end

app/controllers/eyeloupe/configs_controller.rb
# frozen_string_literal: true

module Eyeloupe
  class ConfigsController < ApplicationController

    before_action :set_config, only: [:update]

    def update
      Eyeloupe.configuration.capture = @value == "true"
      cookies[:eyeloupe_capture] = @value
      redirect_to root_path, status: 303
    end

    protected

    def set_config
      @value = params[:value]
    end
  end
end

app/controllers/eyeloupe/data_controller.rb
# frozen_string_literal: true

module Eyeloupe

  class DataController < ApplicationController

    # Delete all data in the database
    # DELETE /data
    def destroy
      Exception.destroy_all
      InRequest.destroy_all
      OutRequest.destroy_all
      redirect_to root_path, status: 303
    end
  end

end

app/controllers/eyeloupe/exceptions_controller.rb
# frozen_string_literal: true

module Eyeloupe
  class ExceptionsController < ApplicationController

    before_action :set_exception, only: %i[ show ]

    # GET /out_requests
    def index
      @pagy, @exceptions = pagy(Exception.all.order(created_at: :desc), items: 50)

      render partial: 'frame' if params[:frame].present?
    end

    # GET /out_requests/1
    def show
      start = @exception.line - 5
      start = 0 if start < 0
      @line_numbers = [*start..@exception.line+6]
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_exception
        @exception = Exception.find(params[:id])
      end

  end
end

app/controllers/eyeloupe/in_requests_controller.rb
# frozen_string_literal: true

module Eyeloupe
  class InRequestsController < ApplicationController
    include Searchable

    before_action :set_in_request, only: [:show]

    def index
      @pagy, @requests = pagy(@query, items: 50)

      render partial: 'frame' if params[:frame].present?
    end

    def show
    end

    protected

    def set_in_request
      @request = InRequest.find(params[:id])
    end
  end
end

app/controllers/eyeloupe/jobs_controller.rb
module Eyeloupe
  class JobsController < ApplicationController
    include Searchable

    before_action :set_job, only: %i[ show ]

    def index
      @pagy, @jobs = pagy(@query, items: 50)

      render partial: 'frame' if params[:frame].present?
    end

    def show
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_job
        @job = Job.find(params[:id])
      end
  end
end

app/controllers/eyeloupe/out_requests_controller.rb
# frozen_string_literal: true

module Eyeloupe
  class OutRequestsController < ApplicationController
    include Searchable

    before_action :set_out_request, only: %i[ show ]

    # GET /out_requests
    def index
      @pagy, @requests = pagy(@query, items: 50)

      render partial: 'frame' if params[:frame].present?
    end

    # GET /out_requests/1
    def show
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_out_request
        @request = OutRequest.find(params[:id])
      end

  end
end

app/helpers/eyeloupe/application_helper.rb
module Eyeloupe
  module ApplicationHelper
    include Pagy::Frontend
  end
end

app/helpers/eyeloupe/jobs_helper.rb
module Eyeloupe
  module JobsHelper
  end
end

app/helpers/eyeloupe/request_helper.rb
# frozen_string_literal: true

module Eyeloupe
  module RequestHelper
    # @param [Eyeloupe::InRequest, Eyeloupe::OutRequest] request The request object
    # @return [String] The formatted response
    def format_response(request)
      type = request.format.to_s != '*/*' ? request.format.to_s : request&.headers
      format(type, request.response)
    end

    # @param [Eyeloupe::InRequest, Eyeloupe::OutRequest] request The request object
    # @return [String] The formatted payload
    def format_payload(request)
      type = request.format.to_s != '*/*' ? request.format.to_s : request&.headers
      format(type, request.payload)
    end

    private

    def format(format, str)
      case format
      when /json/
        JSON.pretty_generate(JSON.parse(str || '{}'))
      when /xml/
        Nokogiri::XML(str || '<></>').to_xml(indent: 2)
      else
        str
      end
    end
  end
end

app/views/eyeloupe/exceptions/_frame.html.erb
<%= turbo_frame_tag "frame" do %>
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">

      <table class="min-w-full divide-y divide-gray-300">
        <thead>
        <tr>
          <th scope="col" class="py-3 pl-4 pr-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Kind</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Count</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Occured</th>
          <th scope="col" class="relative py-3 pl-3 pr-4 sm:pr-0">
            <span class="sr-only">Details</span>
          </th>
        </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @exceptions.each do |ex| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-base font-medium text-gray-900 sm:pl-0">
                <%= ex.kind %>
                <p class="text-sm font-normal text-gray-500"><%= ex.message.truncate(100) %></p>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500"><%= ex.count %></td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500"><%= distance_of_time_in_words(ex.updated_at, DateTime.now) %></td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-base font-medium sm:pr-0">
                <%= link_to "Details", exception_path(ex), class: "text-gray-600 hover:text-gray-900", data: {"turbo_frame": "_top"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <aside class="mt-4 px-4 py-3 flex items-center justify-center sm:px-6" aria-label="Pagination">
      <div class="flex-1 flex justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
    </aside>
  </div>
<% end %>

app/views/eyeloupe/exceptions/index.html.erb
<div class="px-4 sm:px-6 lg:px-8 bg-white rounded-md shadow-md py-5">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold leading-6 text-gray-900">Exceptions</h1>
      <p class="mt-2 text-sm text-gray-700">All exceptions that have been raised in the application.</p>
    </div>
    <div>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <%= turbo_frame_tag "frame", src: exceptions_path(frame: true), data: {"eyeloupe--refresh-target": "frame"} do %><% end %>
  </div>
</div>

app/views/eyeloupe/exceptions/show.html.erb
<div class="px-4 sm:px-6 lg:px-8 bg-white rounded-md shadow-md py-5">
  <div class="px-4 sm:px-0">
    <h3 class="text-xl font-semibold leading-7 text-gray-900">Exception Details</h3>
  </div>
  <div class="mt-6 border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Time</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= @exception.created_at.to_formatted_s(:long) %> (<%= distance_of_time_in_words(@exception.updated_at, DateTime.now) %>)
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Hostname</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @exception.hostname %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Kind</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= @exception.kind %>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Count</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= @exception.count %>
        </dd>
      </div>
      <% if @exception.in_request_id.present? %>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Request</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= link_to "View request", in_request_path(@exception.in_request_id), class: "underline" %>
        </dd>
      </div>
      <% end %>
      <% if @exception.out_request_id.present? %>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-base font-medium leading-6 text-gray-900">Request</dt>
          <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
            <%= link_to "View request", out_request_path(@exception.out_request_id), class: "underline" %>
          </dd>
        </div>
      <% end %>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Message</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0  rounded-md bg-black text-white overflow-x-auto">
          <pre class="p-2"><%= @exception.message %></pre>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Backtrace</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0 rounded-md bg-black text-white overflow-x-auto">
          <pre class="p-2"><%= JSON.parse(@exception.stacktrace).join("\n") %></pre>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Code preview</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0 rounded-md bg-black text-white overflow-x-auto px-2 pt-2">
          <p class="pb-4 font-semibold"><%= @exception.file %></p>
          <% JSON.parse(@exception.location).each_with_index do |line, i| %>
            <div class="grid grid-cols-12 gap-x-1 <%= @line_numbers[i] + 1 == @exception.line ? "bg-red-500 bg-opacity-30" : "" %>">
              <span class="text-right col-span-1 font-medium text-base text-gray-300"><%= @line_numbers[i] + 1 %></span>
              <pre class="col-span-11"><code class="!p-0"><%= line %></code></pre>
            </div>
          <% end %>
        </dd>
      </div>
      <% if Eyeloupe::configuration.openai_access_key.present? %>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0" data-controller="eyeloupe--ai-assistant" data-eyeloupe--ai-assistant-url-value="<%= ai_assistant_response_url(@exception) %>">
        <dt class="text-base font-medium leading-6 text-gray-900">AI Assistant</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <button data-action="eyeloupe--ai-assistant#assist" data-eyeloupe--ai-assistant-target="btn" class="rounded-md px-2 py-1 text-white bg-red-500 text-xl hover:shadow-md hover:bg-red-400 transition flex gap-x-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-robot" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M7 7h10a2 2 0 0 1 2 2v1l1 1v3l-1 1v3a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-3l-1 -1v-3l1 -1v-1a2 2 0 0 1 2 -2z"></path>
              <path d="M10 16h4"></path>
              <circle cx="8.5" cy="11.5" r=".5" fill="currentColor"></circle>
              <circle cx="15.5" cy="11.5" r=".5" fill="currentColor"></circle>
              <path d="M9 7l-1 -4"></path>
              <path d="M15 7l1 -4"></path>
            </svg>
            <span>Click to get some help</span>
          </button>

          <svg data-eyeloupe--ai-assistant-target="loader" width="50" class="hidden" viewBox="0 0 120 30" xmlns="http://www.w3.org/2000/svg" fill="#ff3130">
            <circle cx="15" cy="15" r="15">
              <animate attributeName="r" from="15" to="15"
                       begin="0s" dur="0.8s"
                       values="15;9;15" calcMode="linear"
                       repeatCount="indefinite" />
              <animate attributeName="fill-opacity" from="1" to="1"
                       begin="0s" dur="0.8s"
                       values="1;.5;1" calcMode="linear"
                       repeatCount="indefinite" />
            </circle>
            <circle cx="60" cy="15" r="9" fill-opacity="0.3">
              <animate attributeName="r" from="9" to="9"
                       begin="0s" dur="0.8s"
                       values="9;15;9" calcMode="linear"
                       repeatCount="indefinite" />
              <animate attributeName="fill-opacity" from="0.5" to="0.5"
                       begin="0s" dur="0.8s"
                       values=".5;1;.5" calcMode="linear"
                       repeatCount="indefinite" />
            </circle>
            <circle cx="105" cy="15" r="15">
              <animate attributeName="r" from="15" to="15"
                       begin="0s" dur="0.8s"
                       values="15;9;15" calcMode="linear"
                       repeatCount="indefinite" />
              <animate attributeName="fill-opacity" from="1" to="1"
                       begin="0s" dur="0.8s"
                       values="1;.5;1" calcMode="linear"
                       repeatCount="indefinite" />
            </circle>
          </svg>

          <p data-eyeloupe--ai-assistant-target="result" id="result"></p>
        </dd>
      </div>
      <% end %>
    </dl>
  </div>

</div>

app/views/eyeloupe/in_requests/_frame.html.erb
<%= turbo_frame_tag "frame" do %>

  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
        <tr>
          <th scope="col" class="py-3 pl-4 pr-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Verb</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Path</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Status</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Duration</th>
          <th scope="col" class="px-3 py-3 text-left text-sm font-medium uppercase tracking-wide text-gray-500">Occurred</th>
          <th scope="col" class="relative py-3 pl-3 pr-4 sm:pr-0">
            <span class="sr-only">Details</span>
          </th>
        </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @requests.each do |request| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-base font-medium text-gray-900 sm:pl-0">
                <%= render "eyeloupe/shared/verb", verb: request.verb %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500"><%= request.path.truncate(100) %></td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500">
                <%= render "eyeloupe/shared/status_code", code: request.status %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500"><%= request.duration %> ms</td>
              <td class="whitespace-nowrap px-3 py-4 text-base text-gray-500"><%= distance_of_time_in_words(request.created_at, DateTime.now) %></td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-base font-medium sm:pr-0">
                <%= link_to "Details", in_request_path(request), class: "text-gray-600 hover:text-gray-900", data: {"turbo_frame": "_top"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <aside class="mt-4 px-4 py-3 flex items-center justify-center sm:px-6" aria-label="Pagination">
      <div class="flex-1 flex justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
    </aside>
  </div>
<% end %>

app/views/eyeloupe/in_requests/show.html.erb
<div class="px-4 sm:px-6 lg:px-8 bg-white rounded-md shadow-md py-5">
  <div class="px-4 sm:px-0">
    <h3 class="text-xl font-semibold leading-7 text-gray-900">Request details</h3>
  </div>
  <div class="mt-6 border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Time</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= @request.created_at.to_formatted_s(:long) %> (<%= distance_of_time_in_words(@request.created_at, DateTime.now) %>)
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Hostname</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @request.hostname %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Method</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= render "eyeloupe/shared/verb", verb: @request.verb %>
        </dd>
      </div>
      <% if @request.controller.present? %>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Controller</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @request.controller %></dd>
      </div>
      <% end %>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Path</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @request.path %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Status</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= render "eyeloupe/shared/status_code", code: @request.status %>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Duration</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= @request.duration %> ms
          <% if @request.db_duration.present? && @request.view_duration.present? %>
          (ActiveRecord: <%= @request.db_duration %> ms, Views: <%= @request.view_duration %> ms)
          <% end %>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">IP Address</dt>
        <dd class="mt-1 text-base leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @request.ip %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Payload</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0 rounded-md bg-black text-white overflow-x-auto">
          <% if @request.payload.present? %>
          <pre class="p-2"><%= format_payload @request %></pre>
          <% else %>
          <p class="text-gray-400 p-2">No payload</p>
          <% end %>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Headers</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0  rounded-md bg-black text-white overflow-x-auto">
          <pre class="p-2"><%= JSON.pretty_generate(JSON.parse(@request.headers || "{}")) %></pre>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Session</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0 rounded-md bg-black text-white overflow-x-auto">
          <pre class="p-2" ><%= JSON.pretty_generate(JSON.parse(@request.session || "{}")) %></pre>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-base font-medium leading-6 text-gray-900">Response</dt>
        <dd class="mt-1 text-base leading-6 sm:col-span-2 sm:mt-0 rounded-md bg-black text-white overflow-x-auto">
          <pre class="p-2"><%= format_response @request %></pre>
        </dd>
      </div>
    </dl>
  </div>
</div>

<% if @request.exception.present? %>
<div class="mt-6 bg-white rounded-md shadow-md py-5">
  <h3 class="text-base font-semibold leading-6 text-gray-900 px-4 sm:px-6 lg:px-8 border-b border-gray-100 pb-3">Exceptions</h3>

  <%= link_to exception_path(@request.exception), class: "text-gray-600 hover:text-gray-900 hover:bg-gray-100 block px-4 sm:px-6 lg:px-8", data: {"turbo_frame": "_top"} do %>
  <div class="divide-y divide-gray-100 px-0 flex justify-between">
    <div class="whitespace-nowrap py-4 pl-4 pr-3 text-base font-medium text-gray-900 sm:pl-0">
      <%= @request.exception.kind %>
      <p class="text-sm font-normal text-gray-500"><%= @request.exception.message %></p>
    </div>
  </div>
  <% end %>

</div>
<% end %>